export const certifications = [
    {
        id: 1,
        title: "Python Masterclass 2023",
        issuer: "Udemy",
        date: "Issued 2023",
        credentialId: "UDEMY-DEMO",
        skills: ["Web Development", "Full Stack"],
        image: "https://upload.wikimedia.org/wikipedia/commons/e/e3/Udemy_logo.svg",
        certificateImage: "/certificates/udemy1.jpg",
        credentialUrl: "#",
        category: "course",
        featured: true
    },
    {
        id: 2,
        title: "HackerRank Python Certification",
        issuer: "HackerRank",
        date: "Issued 2023",
        credentialId: "HR-DEMO",
        skills: ["Problem Solving", "Algorithms"],
        image: "/certificates/Hackerank.jpg",
        certificateImage: "/certificates/Hackerank.jpg",
        credentialUrl: "#",
        category: "course",
        featured: false
    },
    {
        id: 3,
        title: "Python Certification",
        issuer: "Python Institute",
        date: "Issued 2023",
        credentialId: "PY-DEMO",
        skills: ["Python", "Programming"],
        image: "/certificates/Python1.jpg",
        certificateImage: "/certificates/Python1.jpg",
        credentialUrl: "#",
        category: "course",
        featured: false
    },
    {
        id: 4,
        title: "C Programming Certification",
        issuer: "Greate Learning",
        date: "Issued 2023",
        credentialId: "C-DEMO",
        skills: ["C", "Programming"],
        image: "/certificates/Clang.jpg",
        certificateImage: "/certificates/Clang.jpg",
        credentialUrl: "#",
        category: "course",
        featured: false
    },
    {
        id: 5,
        title: "HTML Certification",
        issuer: "Greate Learning",
        date: "Issued 2023",
        credentialId: "HTML-DEMO",
        skills: ["HTML", "Web Design"],
        image: "/certificates/Html.jpg",
        certificateImage: "/certificates/Html.jpg",
        credentialUrl: "#",
        category: "course",
        featured: false
    },
    {
        id: 6,
        title: "Scilab Certification",
        issuer: "NBNSCOE",
        date: "Issued 2023",
        credentialId: "SCILAB-DEMO",
        skills: ["Scilab", "Computation"],
        image: "/certificates/Scilab.jpg",
        certificateImage: "/certificates/Scilab.jpg",
        credentialUrl: "#",
        category: "course",
        featured: false
    },
    {
        id: 7,
        title: "VS Code Certification",
        issuer: "Greate Learning",
        date: "Issued 2023",
        credentialId: "VSCODE-DEMO",
        skills: ["VS Code", "IDE"],
        image: "/certificates/VsCode.jpg",
        certificateImage: "/certificates/VsCode.jpg",
        credentialUrl: "#",
        category: "course",
        featured: false
    },
    {
        id: 8,
        title: "ChatGPT Certification",
        issuer: "-",
        date: "Issued 2023",
        credentialId: "GPT-DEMO",
        skills: ["AI", "Prompt Engineering"],
        image: "/certificates/Chatgpt.jpg",
        certificateImage: "/certificates/Chatgpt.jpg",
        credentialUrl: "#",
        category: "course",
        featured: false
    },
    {
        id: 9,
        title: "Python Test Series Winner",
        issuer: "NBNSCOE",
        date: "Issued 2023",
        credentialId: "WINNER-DEMO",
        skills: ["Python", "Competition"],
        image: "/certificates/Python Test Series Runner -Winner Certificates-1_page-0001.jpg",
        certificateImage: "/certificates/Python Test Series Runner -Winner Certificates-1_page-0001.jpg",
        credentialUrl: "#",
        category: "winner",
        featured: false
    },
    {
        id: 10,
        title: "AWS Certification",
        issuer: "AWS",
        date: "Issued 2023",
        credentialId: "AWS-DEMO",
        skills: ["Cloud", "AWS"],
        image: "/certificates/aws.jpg",
        certificateImage: "/certificates/aws.jpg",
        credentialUrl: "#",
        category: "course",
        featured: false
    },
    {
        id: 11,
        title: "Code-A-Thon 2023",
        issuer: "Savali Foundation & Eshwar Foundation",
        date: "Issued 2023",
        credentialId: "CAT-23",
        skills: ["Coding", "Hackathon"],
        image: "/certificates/code-a-thon-2023.png",
        certificateImage: "/certificates/code-a-thon-2023.png",
        credentialUrl: "#",
        category: "participation",
        featured: false
    },
    {
        id: 12,
        title: "Code-A-Thon 2025",
        issuer: "Savali Foundation & Eshwar Foundation",
        date: "Issued 2025",
        credentialId: "CAT-25",
        skills: ["Coding", "Hackathon"],
        image: "/certificates/code-a-thon-2025.png",
        certificateImage: "/certificates/code-a-thon-2025.png",
        credentialUrl: "#",
        category: "participation",
        featured: false
    },
    {
        id: 13,
        title: "CodeSoft Internship",
        issuer: "CodeSoft",
        date: "Issued 2023",
        credentialId: "CS-DEMO",
        skills: ["Internship", "Development"],
        image: "/certificates/codesoft.jpg",
        certificateImage: "/certificates/codesoft.jpg",
        credentialUrl: "#",
        category: "participation",
        featured: false
    },
    {
        id: 14,
        title: "Dishta Certification",
        issuer: "NBNSCOE",
        date: "Issued 2023",
        credentialId: "DISHTA-DEMO",
        skills: ["Training"],
        image: "/certificates/dishta.jpg",
        certificateImage: "/certificates/dishta.jpg",
        credentialUrl: "#",
        category: "participation",
        featured: false
    },
    {
        id: 15,
        title: "Free Fire Tournament",
        issuer: "NBNSCOE",
        date: "Issued 2023",
        credentialId: "FF-DEMO",
        skills: ["Gaming", "Strategy"],
        image: "/certificates/free fire.png",
        certificateImage: "/certificates/free fire.png",
        credentialUrl: "#",
        category: "Runner",
        featured: false
    },
    {
        id: 16,
        title: "Hackathon Participation",
        issuer: "Sveri College Of Engineering,Pandharpur",
        date: "Issued 2023",
        credentialId: "HACK-1",
        skills: ["Hackathon", "Teamwork"],
        image: "/certificates/hackathon1.jpg",
        certificateImage: "/certificates/hackathon1.jpg",
        credentialUrl: "#",
        category: "participation",
        featured: false
    },
    {
        id: 17,
        title: "Hackathon Participation II",
        issuer: "SKN SINHGAD COLLEGE OF ENGINEERING, PANDHARPUR",
        date: "Issued 2023",
        credentialId: "HACK-2",
        skills: ["Hackathon", "Innovation"],
        image: "/certificates/Hackathon2.jpg",
        certificateImage: "/certificates/Hackathon2.jpg",
        credentialUrl: "#",
        category: "participation",
        featured: false
    },
    {
        id: 18,
        title: "Hackathon Participation III",
        issuer: "SKN SINHGAD COLLEGE OF ENGINEERING, PANDHARPUR",
        date: "Issued 2023",
        credentialId: "HACK-3",
        skills: ["Hackathon", "Coding"],
        image: "/certificates/hackathon3.jpg.png",
        certificateImage: "/certificates/hackathon3.jpg.png",
        credentialUrl: "#",
        category: "participation",
        featured: false
    },
    {
        id: 19,
        title: "IC-SFSR 2024",
        issuer: "NBNSCOE",
        date: "Issued 2024",
        credentialId: "ICSFSR-24",
        skills: ["Conference", "Research"],
        image: "/certificates/ic-sfsr-24.png",
        certificateImage: "/certificates/ic-sfsr-24.png",
        credentialUrl: "#",
        category: "participation",
        featured: false
    },
    {
        id: 20,
        title: "Innovation Tech",
        issuer: "NBNSCOE",
        date: "Issued 2023",
        credentialId: "INN-TECH",
        skills: ["Innovation", "Technology"],
        image: "/certificates/innovation_tech.png",
        certificateImage: "/certificates/innovation_tech.png",
        credentialUrl: "#",
        category: "participation",
        featured: false
    },
    {
        id: 21,
        title: "Kaggle Certification",
        issuer: "Kaggle",
        date: "Issued 2023",
        credentialId: "KAGGLE-DEMO",
        skills: ["Data Science", "Machine Learning"],
        image: "/certificates/kaggle.jpg",
        certificateImage: "/certificates/kaggle.jpg",
        credentialUrl: "#",
        category: "course",
        featured: false
    },
    {
        id: 22,
        title: "Olympus 2K24 Winner",
        issuer: "SKN SINHGAD COLLEGE OF ENGINEERING, PANDHARPUR",
        date: "Issued 2024",
        credentialId: "OLY-WIN",
        skills: ["Competition", "Winner"],
        image: "/certificates/olympus-2k24-winner-mirror-code.png",
        certificateImage: "/certificates/olympus-2k24-winner-mirror-code.png",
        credentialUrl: "#",
        category: "winner",
        featured: false
    },
    {
        id: 23,
        title: "Olympus 2K24 RUNNER",
        issuer: "SKN SINHGAD COLLEGE OF ENGINEERING, PANDHARPUR",
        date: "Issued 2024",
        credentialId: "OLY-PART",
        skills: ["Competition", "Participation"],
        image: "/certificates/olympus-2k24.png",
        certificateImage: "/certificates/olympus-2k24.png",
        credentialUrl: "#",
        category: "Runner",
        featured: false
    },
    {
        id: 24,
        title: "Pryog",
        issuer: "NBNSCOE",
        date: "Issued 2023",
        credentialId: "PRYOG-1",
        skills: ["Project", "Exhibition"],
        image: "/certificates/pryog.jpg",
        certificateImage: "/certificates/pryog.jpg",
        credentialUrl: "#",
        category: "participation",
        featured: false
    },
    {
        id: 25,
        title: "Pryog 2K24 WINNER",
        issuer: "NBNSCOE",
        date: "Issued 2024",
        credentialId: "PRYOG-24",
        skills: ["Project", "Exhibition"],
        image: "/certificates/pryog2k24.jpg",
        certificateImage: "/certificates/pryog2k24.jpg",
        credentialUrl: "#",
        category: "winner",
        featured: false
    },
    {
        id: 26,
        title: "Python NPTEL",
        issuer: "NPTEL",
        date: "Issued 2023",
        credentialId: "NPTEL-PY",
        skills: ["Python", "Academic"],
        image: "/certificates/pytgon_nptl.jpg",
        certificateImage: "/certificates/pytgon_nptl.jpg",
        credentialUrl: "#",
        category: "course",
        featured: true
    },
    {
        id: 27,
        title: "SPECTRUN 2K24 RUNNER IN CODE MIND CLASH",
        issuer: "SKN SINHGAD COLLEGE OF ENGINEERING, PANDHARPUR",
        date: "Issued 2023",
        credentialId: "SPEC-DEMO",
        skills: ["Event", "Participation"],
        image: "/certificates/spectrum.png",
        certificateImage: "/certificates/spectrum.png",
        credentialUrl: "#",
        category: "Runner",
        featured: false
    },
    {
        id: 28,
        title: "TECHFEST PROJECT-EXPO WINNER",
        issuer: "A.G. PATIL INSTITUTE OF TECHNOLOGY , SOLAPUR",
        date: "Issued 2023",
        credentialId: "TECH-DEMO",
        skills: ["Techfest", "Participation"],
        image: "/certificates/techfest.jpg",
        certificateImage: "/certificates/techfest.jpg",
        credentialUrl: "#",
        category: "winner",
        featured: true
    },
    {
        id: 29,
        title: "TECHNO-SINH 2K24 BUG BLSATING RUNNER",
        issuer: "Unknown",
        date: "Issued 2023",
        credentialId: "TECHNO-DEMO",
        skills: ["Technical", "Event"],
        image: "/certificates/technosinh.png",
        certificateImage: "/certificates/technosinh.png",
        credentialUrl: "#",
        category: "Runner",
        featured: false
    },
    {
        id: 30,
        title: "WisoTech CODE WAR RUNNER",
        issuer: "V.V.P. INSTITUTE OF ENGINEERING & TECHNOLOGY, SOLAPUR",
        date: "Issued 2023",
        credentialId: "WISO-1",
        skills: ["Tech", "Event"],
        image: "/certificates/wisoTech.jpg",
        certificateImage: "/certificates/wisoTech.jpg",
        credentialUrl: "#",
        category: "Runner",
        featured: false
    },
    {
        id: 31,
        title: "WISO TECH 2K24 PROJECT-EXHIBITION WINNER",
        issuer: "V.V.P. INSTITUTE OF ENGINEERING & TECHNOLOGY, SOLAPUR",
        date: "Issued 2023",
        credentialId: "WISO-PROJ",
        skills: ["Project", "Presentation"],
        image: "/certificates/wisoTech_project.jpg",
        certificateImage: "/certificates/wisoTech_project.jpg",
        credentialUrl: "#",
        category: "winner",
        featured: false
    },
    {
        id: 32,
        title: "WiTech 2K23 TECH-QUIZ",
        issuer: "WALCHA INSTITUTE OF TECHNOLOGY, SOLAPUR",
        date: "Issued 2023",
        credentialId: "WITECH-23",
        skills: ["Tech", "Event"],
        image: "/certificates/witech-2k23.png",
        certificateImage: "/certificates/witech-2k23.png",
        credentialUrl: "#",
        category: "participation",
        featured: false
    },
    {
        id:33,
        title:"Hackathon III SKN",
        issuer:"SKN SINHGAD COLLEGE OF ENGINEERING, PANDHARPUR",
        date:"Issued 29th March 2025",
        credentialId:"HACK-3",
        skills:["Hackathon", "Event"],
        image:"/certificates/hackathon3.png",
        certificateImage:"/certificates/hackathon3.png",
        credentialUrl:"#",
        category:"participation",
        featured:false
    }
]
