export const projects = [
    {
        id: 1,
        name: "E-Commerce Platform",
        description: "A full-stack e-commerce solution with payment integration, user authentication, and admin dashboard.",
        image: "https://images.unsplash.com/photo-1557821552-17105176677c?w=800&h=500&fit=crop",
        technologies: ["React", "Node.js", "MongoDB", "Stripe", "Redux", "Express"],
        github: "https://github.com",
        demo: "https://demo.com",
        featured: true,
        category: "Full Stack",
        longDescription: "A comprehensive e-commerce platform built with React and Node.js. Features include user authentication, product management, shopping cart functionality, secure payment processing with Stripe, order tracking, and an admin dashboard for managing products and orders."
    },
    {
        id: 2,
        name: "AI Chat Application",
        description: "Real-time chat application powered by AI with message encryption and file sharing capabilities.",
        image: "https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?w=800&h=500&fit=crop",
        technologies: ["Next.js", "OpenAI", "Socket.io", "PostgreSQL", "Prisma", "TypeScript"],
        github: "https://github.com",
        demo: "https://demo.com",
        featured: true,
        category: "AI/ML",
        longDescription: "An intelligent chat application that leverages OpenAI's GPT models for AI-powered conversations. Features real-time messaging using Socket.io, end-to-end encryption, file sharing, chat history, and user presence indicators."
    },
    {
        id: 3,
        name: "Task Management Tool",
        description: "Collaborative project management platform with Kanban boards, time tracking, and team analytics.",
        image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=500&fit=crop",
        technologies: ["Vue.js", "Firebase", "Tailwind", "Chart.js", "Vuex"],
        github: "https://github.com",
        demo: "https://demo.com",
        featured: true,
        category: "Productivity",
        longDescription: "A collaborative project management tool featuring Kanban boards for task organization, time tracking capabilities, team collaboration features, real-time updates, and comprehensive analytics dashboards to track team productivity and project progress."
    },
    {
        id: 4,
        name: "Weather Dashboard",
        description: "Interactive weather forecasting app with real-time data, maps, and weather alerts for multiple locations.",
        image: "https://images.unsplash.com/photo-1592210454359-9043f067919b?w=800&h=500&fit=crop",
        technologies: ["React", "Weather API", "Mapbox", "Redux", "Chart.js"],
        github: "https://github.com",
        demo: "https://demo.com",
        featured: false,
        category: "Web App",
        longDescription: "A comprehensive weather forecasting application that provides real-time weather data, interactive maps, 7-day forecasts, severe weather alerts, and location-based weather tracking for multiple cities worldwide."
    },
    {
        id: 5,
        name: "Fitness Tracker",
        description: "Personal fitness tracking application with workout plans, nutrition tracking, and progress analytics.",
        image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&h=500&fit=crop",
        technologies: ["React Native", "Express", "MySQL", "D3.js", "JWT"],
        github: "https://github.com",
        demo: "https://demo.com",
        featured: false,
        category: "Mobile App",
        longDescription: "A comprehensive fitness tracking mobile application with customizable workout plans, nutrition and calorie tracking, progress visualization with D3.js charts, goal setting, and achievement badges to keep users motivated."
    },
    {
        id: 6,
        name: "Social Media Dashboard",
        description: "Analytics dashboard for managing multiple social media accounts with scheduling and insights.",
        image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=500&fit=crop",
        technologies: ["React", "Node.js", "MongoDB", "Twitter API", "Instagram API"],
        github: "https://github.com",
        demo: "https://demo.com",
        featured: false,
        category: "Marketing",
        longDescription: "A unified dashboard for managing multiple social media accounts. Features include post scheduling, engagement analytics, follower growth tracking, content performance insights, and automated posting across platforms."
    },
    {
        id: 7,
        name: "Cryptocurrency Portfolio Tracker",
        description: "Track your crypto investments with real-time prices, portfolio analytics, and market insights.",
        image: "https://images.unsplash.com/photo-1621761191319-c6fb62004040?w=800&h=500&fit=crop",
        technologies: ["Next.js", "CoinGecko API", "TailwindCSS", "Recharts"],
        github: "https://github.com",
        demo: "https://demo.com",
        featured: false,
        category: "Finance",
        longDescription: "A cryptocurrency portfolio management application with real-time price tracking, portfolio performance analytics, profit/loss calculations, historical data visualization, and market trend analysis for informed investment decisions."
    },
    {
        id: 8,
        name: "Recipe Finder App",
        description: "Discover and save recipes with ingredient search, nutritional information, and meal planning.",
        image: "https://images.unsplash.com/photo-1495521821757-a1efb6729352?w=800&h=500&fit=crop",
        technologies: ["React", "Spoonacular API", "Firebase", "Material-UI"],
        github: "https://github.com",
        demo: "https://demo.com",
        featured: false,
        category: "Lifestyle",
        longDescription: "A comprehensive recipe discovery app that helps users find recipes based on available ingredients, dietary preferences, and nutritional requirements. Features include meal planning, grocery list generation, and favorite recipe collections."
    },
    {
        id: 9,
        name: "Online Code Editor",
        description: "Browser-based code editor with syntax highlighting, live preview, and collaborative editing.",
        image: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800&h=500&fit=crop",
        technologies: ["React", "CodeMirror", "Socket.io", "Node.js", "WebRTC"],
        github: "https://github.com",
        demo: "https://demo.com",
        featured: false,
        category: "Developer Tools",
        longDescription: "A powerful browser-based code editor with syntax highlighting for multiple languages, live preview for HTML/CSS/JavaScript, real-time collaborative editing, code sharing, and integrated terminal for running code snippets."
    },
    {
        id: 10,
        name: "Event Management System",
        description: "Complete event management platform with ticketing, attendee tracking, and event analytics.",
        image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&h=500&fit=crop",
        technologies: ["Vue.js", "Express", "PostgreSQL", "Stripe", "SendGrid"],
        github: "https://github.com",
        demo: "https://demo.com",
        featured: false,
        category: "Business",
        longDescription: "A comprehensive event management system that streamlines event creation, ticket sales, attendee registration, email notifications, QR code check-ins, and provides detailed analytics on event performance and attendee engagement."
    },
    {
        id: 11,
        name: "Real Estate Listing Platform",
        description: "Property listing platform with advanced search, virtual tours, and agent management.",
        image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=500&fit=crop",
        technologies: ["Next.js", "Prisma", "PostgreSQL", "Google Maps API", "AWS S3"],
        github: "https://github.com",
        demo: "https://demo.com",
        featured: false,
        category: "Real Estate",
        longDescription: "A modern real estate platform with advanced property search filters, interactive maps, virtual property tours, agent profiles, appointment scheduling, and mortgage calculator to help buyers find their perfect home."
    },
    {
        id: 12,
        name: "Learning Management System",
        description: "Educational platform with course creation, video lectures, quizzes, and student progress tracking.",
        image: "https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=800&h=500&fit=crop",
        technologies: ["React", "Node.js", "MongoDB", "AWS S3", "Stripe", "JWT"],
        github: "https://github.com",
        demo: "https://demo.com",
        featured: false,
        category: "Education",
        longDescription: "A comprehensive learning management system that enables instructors to create and manage courses, upload video lectures, create quizzes and assignments, track student progress, and facilitate online learning with discussion forums and live sessions."
    }
]
